name: AutoComment
on:
  issues:
    types: [opened]
jobs:
  featured_criteria_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Testing Values
            
            - [ ] Support activity and quality
              - Approved/Rejected by: @
            - [ ] Documentation quality
              - Approved/Rejected by: @
            - [ ] Modlist has custom patching
              - Approved/Rejected by: @
            - [ ] No obvious unresolved conflicts
              - Approved/Rejected by: @
            - [ ] No frequent crashes or repeatable bugs
              - Approved/Rejected by: @
            
            ## Important Meta Data
            
            - [ ] Modlist Image as WEBP
              - Approved/Rejected by: @
            - [ ] Modlist Description/Elevator Pitch
              - Approved/Rejected by: @
            - [ ] Modlist location in the Find a List system
              - Approved/Rejected by: @
            - [ ] Link to LoadOrder Library page for the List
              - Approved/Rejected by: @

